ask_panichkina/ask_panichkina/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from ask_panichkina.views import index, login, signup, ask_question,question

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ask_panichkina.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    #url(r'^helloworld/', 'ask_panichkina.views.helloworld', name='helloworld'),
    url(r'^(\w*)$', index, name='index'),
#    url(r'^$', index, name='index'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^login/$', login, name='login'),
    url(r'^ask_question/$', ask_question, name='ask_question'),
    url(r'^question/(\d+)/$', question, name='question'),

)

ask_panichkina/ask_panichkina/models.py
#!/usr/bin/env python
from django.db import models
from django.contrib.auth.models import User
from ask_panichkina import settings

import os
import sys


uploads = "avatars"

class Tag(models.Model):
    text = models.CharField(max_length=15)

class Question(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=60)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)
    likes_num = models.IntegerField(default=0)
    is_deleted = models.BooleanField(default=False)
    def __unicode__(self):
        return self.title

class Answer(models.Model):
    author = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    likes_num = models.IntegerField(default=0)


class Profile(models.Model):
    user = models.OneToOneField(User)
    rating = models.IntegerField(default=0)
    avatar = models.ImageField(upload_to=uploads, default="/avatar.jpg")



class Rate_question(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)


class Rate_answer(models.Model):
    user = models.ForeignKey(User)
    answer = models.ForeignKey(Answer)


class Rate_profile(models.Model):
    user = models.ForeignKey(User)
    profile = models.ForeignKey(Profile)

ask_panichkina/ask_panichkina/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import hashlib
import os
import json
import datetime
from ask_panichkina.models import Question, Tag, Answer, Profile, Rate_answer, Rate_profile, Rate_question
#@csrf_exempt
#def helloworld(request):
#	output = '<b>Hello World!Broooo</b><br />'
#	if request.method == 'GET':
#		output += 'Get query: '
#		for x in request.GET:
#			output+= '<br/>'
#			params = request.GET.getlist(x)
#			output += '<b>' + x + '</b>' + ':'
#			for param in params:
#				output += '<br/>' + param
#	else:
#		output += 'Post query: '
#		for x in request.POST:
#			output+= '<br/>'
#			params = request.POST.getlist(x)
#			output += '<b>' + x + '</b>' + ':'
#			for param in params:
#				output += '<br/>' + param
#	html = "<html><body>%s</body></html>" % output
#	return HttpResponse(html)



def question(request, id):
    data = {
        'id' : int(id),
    }
    return HttpResponse(json.dumps(data), content_type = 'application/json')

def index(request, order = ''):
#   questions =Question.objects.all()
#    questions = Question.objects.filter(is_deleted=0).order_by('-likes_num')
    if order == 'best':
        questions = Question.objects.filter(is_deleted = 0).order_by('-likes_num')
    else:
        questions = Question.objects.filter(is_deleted = 0).order_by('-date')

    return render(request,'index.html',{'questions' : questions, 'order':order})



def signup(request):
    return render(request, 'signup.html',())

def login(request):
    return render(request, 'login.html', ())

def ask_question(request):
    return render(request, 'ask_question.html', ())

ask_panichkina/templates/ask_question.html
{% extends "layout.html" %}

{% block main %}

<div class="container">
<div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6">
      <form class="form-horizontal" method="POST">
          {% csrf_token %}
      <fieldset>

        <form method="post" action="/registration/signup" class="form-horizontal" enctype="multipart/form-data">
	    <input type="hidden" name="signup_form" value="register">

    	<div class="row">
            <h3>New question</h3>
        </div>
        <br>
        <div class="row">
		<div class="span2">
			<label for="title">Title</label>
            <div class="col-md-9">
                <span class="label label-danger">{{ error }}</span>
            </div>
		</div>

		<div class="span5">
			<input id="" name="" type="text" required value="" style="resize: none; width: 100%; height: 100px">
		</div>
	    </div>
	    <br>

	    <div class="row">
		<div class="span2">
			<label for="description">Descruption</label>
		</div>
		<div class="span5" >
			<input id="" name="" type="text" required value="" style="resize: none; width: 100%; height: 300px">
		</div>
	</div>
	    <br>

	    <div class="row">
		<div class="span2">
			<label for="tags">Tags</label>
		</div>
		<div class="span5">
			<input id="" name="" type="text" required value="" style="resize: none; width: 100%">
		</div>
	</div>
	    <br>

	    <div class="row">
        <div class="span1 offset4">
            <button class="btn btn-primary btn-block" type="submit">Ask!</button>
            <input type="hidden" name="next" value="">
        </div>
	</div>
      </form>

      </fieldset>
      </form>
    </div>
  </div>
</div>

{% endblock %}

ask_panichkina/templates/index.html
{% extends "layout.html" %}

{% block main %}

 	    <h2>Tag: {{tag}}</h2>
        <div class="btn-group" role="group">
                      <a href="{% url 'index' 'new'%}" class="btn btn-default {% if order == 'new'%} active {% endif %}" role="button">New</a>
                      <a href="{% url 'index' 'best'%}" class="btn btn-default {% if order == 'best'%} active {% endif %}" role="button">Best</a>
                </div>

        {% for Question in questions %}
		<div class = "question row panel panel-default" style="background-color: #ffffff">
			<div class = "span3">
				<div align="center">
					<img src="avatar.jpg" class="media-object" style="margin: 5px" width=150 heigth=150 alt=""/>
 				</div>
 				<div align="center">
					 <h1>{{Question.author}}</h1>
				</div>
                <div align="center">
					<a class="btn btn-inverse" href="" data-liketype="q" data-vote="-" data-id="" data-url="/like">-</a>
                    <span class="badge">{{ Question.likes_num }}</span>
					<a class="btn btn-inverse" href="" data-liketype="q" data-vote="+" data-id="" data-url="/like">+</a>
				</div>
			</div>

			<div class = "span5">
				<a href="#"> <h3>{{Question.title}}</h3> </a>
				<hr/>
				<div class="questiontext">
					<p>{{Question.text}}</p>
				</div>
			</div>



			<div class="span5">
			<p>{{Question.date_added}}</p>
			<p>
			<h4 href="/question?id={{Question.id}}">Answer ({{Question.answer_set.count}})</h4>
				<span style="margin-left: 5%;">
					{% if Question.tag_set.all %}
					Tags:
					{% for tag in Question.tag_set.all %}
						<a href="/tag?tag={{tag.tag_word}}">{{tag.tag_word}} </a>
					{% endfor %}
					{% endif %}
				</span>
			</p>
			</div>
		</div>
        {% endfor %}



	<div class="pagination">
		<ul>
			<li> <a href= "">First</a> </li>
			<li>
			{% if question_page.has_previous %}
				<a href= "">Prev</a>
			{% endif %}
			</li>

			{% for page in question_page.paginator.page_range %}
			{% if page < max_page and page > min_page %}
			<li class="{% if question_page.number == page %}active{% endif %} "> <a href=""> {{page}} </a> </li>
			{% endif %}
			{% endfor %}

			<li>
			{% if question_page.has_next %}
				<a href= "">Next</a>
			{% endif %}
			</li>
			<li> <a href= "">Last</a> </li>
		</ul>
    </div>


{% endblock %}

ask_panichkina/templates/layout.html
<!DOCTYPE html>
<html>
	<head>
		<title>Ask_Panichkina</title>
		<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css"/>
		<link rel="stylesheet" href="/css/style.css"/>
		<script src="/css/jquery-2.1.3.js"></script>
        <script type="text/javascript" src="/bootstrap/js/bootstrap.js"></script>
	</head>
	<body style="background-color: #d9edf7">
        <div class="container">
		<div class="navbar navbar-inverse">
      		<div class="navbar-inner">
        		<div class="container">
          			<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            			<span class="icon-bar"></span><span class="icon-bar"></span>
           				<span class="icon-bar"></span>
          			</button>
          			<a class="brand" href="/">AskPanichkina</a>
          			<div class="nav-collapse collapse">
            			<ul class="nav">
            				<form class="navbar-search pull-left">
  								<input type="text" class="search-query" placeholder="Search" >
  								<button class="navbar-btn btn-inverse" type="submit">
                                    <i class="icon-search icon-white"></i>
                                </button>
                                <button class="btn btn-inverse"  type="submit" style = "margin: 5px">
                                   <a  href="/ask_question">ASK!</a>
                                </button>
							</form>
            			</ul>
            			<ul class="nav pull-right"><!--
                            <li><img class = "img-rounded" style = "margin: 5px" src="avatar.jpg" heigth="30" width="30" alt=""/></li>
							<button type="button" class="btn btn-inverse" data-toggle="dropdown"  style="font-size: 12pt">username
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li> <a href="/ask_question">Settings</a> </li>
                                <li> <a href="/logout">Log out</a> </li>
                            </ul>
                             -->
              				<li>
                				<a href="/signup">Sign up</a>
              				</li>
              				<li>
                				<a href="/login">Log in</a>
              				</li>

            			</ul>
          			</div>
        		</div>
      		</div>
    	</div>
        </div>
		<div class="container">
  			<div class="row-fluid">
    			<div class="span7 offset1">
     		 		{% block main %}
     		 		{% endblock %}
    			</div>
    			<div class="span3 offset1">
    				<ul class="authors_or_tags">
    					<h2>Popular Tags</h2>
  						<li>Drugs</li>
  						<li>Hope</li>
					</ul>
    				<ul class="authors_or_tags">
    					<h2>Best Members</h2>
  						<li>Dog</li>
  						<li>Mr.Purpyr</li>
					</ul>					
     			 <!--Body content-->
    			</div>
  			</div>
		</div>
	</body>
</html>

ask_panichkina/templates/login.html
{% extends "layout.html" %}

{% block main %}
   <div class="container col-md-3">
  <form class="form">

    <h2 class="row">Log in</h2>
    <div class="row">
        <div class="span2">
			<label for="id_username">Login</label>
		</div>
		<div class="span5">
			<input id="id_username" class="form-control" name="login" type="text" required>
		</div>
	</div>
    <div class="row">
        <div class="span2">
            <label for="id_password">Password</label>
		</div>
		<div class="span5">
			<input id="id_password" class="form-control" name="password" type="password" required>
		</div>
    </div>
    <div class="row">
        <div class="span5 offset2">
            <button class="btn btn-outline-inverse btn-lg" type="submit">Log in!</button>
            <input type="hidden" name="next" value="">
        </div>
    </div>
    <div class="row">
        <div class="span3 offset2">
            <a href="/signup">Create new account</a>
		</div>
	</div>
  </form>

</div> <!-- /container -->
{% endblock %}

ask_panichkina/templates/signup.html
{% extends "layout.html" %}

{% block main %}
     <div class="container col-md-3">
  <form class="form">
<div class="row">
			<div class="span8">
<h2>Registration</h2>
<br>

<form method="post" action="/registration/signup" class="form-horizontal" enctype="multipart/form-data">
	<input type="hidden" name="signup_form" value="register">

	<div class="row">
		<div class="span2">
			<label for="id_username">Username</label>
		</div>
		<div class="span5">
			<input id="id_username" name="username" type="text" required value="">
		</div>
	</div>
	<br>


	<div class="row">
		<div class="span2">
			<label for="id_email">Email address</label>
		</div>
		<div class="span5">
			<input id="id_email" name="email" type="email" required value="">
		</div>
	</div>
	<br>


	<div class="row">
		<div class="span2">
			<label for="id_password1">Password</label>
		</div>
		<div class="span5">
			<input id="id_password1" name="password1" type="password" required value="">
		</div>
	</div>
	<br>


	<div class="row">
		<div class="span2">
			<label for="id_password2">Password confirmation</label>
		</div>
		<div class="span5">
			<input id="id_password2" name="password2" type="password" required value="">
		</div>
	</div>
	<br>



	<div class="row">
		<div class="span2">
			<p>Upload avatar</p>
		</div>
		<div class="span5">

			<div> <input id="id_avatar" name="avatar" type="file"> </div>
		</div>
	</div>
	<br>
	<div class="row">
        <div class="span5 offset2">
            <button class="btn btn-outline-inverse btn-lg" type="submit">Register!</button>
            <input type="hidden" name="next" value="">
        </div>
	</div>
</form>
    </div>
	</div>
        </form>

</div> <!-- /container -->
{% endblock %}